# Generated by Django 4.0.4 on 2022-05-24 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='Content',
            new_name='content',
        ),
    ]
